version: "3.8"

services:
  php:
    build: ./docker/php
    container_name: php
    environment:
      PHP_IDE_CONFIG: "serverName=Jupiter"
      # Variables to connect to our Postgres server.
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: murmur
      PGPORT: 5432
      # Hostname of our Postgres container.
      PGHOST: db
    ports:
      - "8000:9000"
    networks:
      - symfony_app
    depends_on:
      # The DB container needs to be started before we start this container.
      - db
    volumes:
      - ./:/var/www/murmur_api:cached
      - ./docker/php/conf/zzz-docker.ini:/usr/local/etc/php/conf.d/zzz-docker.ini
    restart: always

  db:
    # We use the predefined Postgres image.
    image: postgres:16.1
    environment:
      # Set user/password for Postgres.
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data.
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - symfony_app
    restart: always
    volumes:
      - /home/gfauconnet/projets/pgdata:/var/lib/postgresql/data

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/murmur_api:cached
    ports:
      - "80:80"
    networks:
      - symfony_app

networks:
  symfony_app:
